// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkfjgvvluuzbkjkdvhah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZmpndnZsdXV6Ymtqa2R2aGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzg1MzIsImV4cCI6MjA2NjcxNDUzMn0.-d1yOBEVnZSYww3rov01BNWD-WyhQ2o4CG5rhHt7jBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);